/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AyaServicesRouteImport } from './routes/aya-services'
import { Route as BabyCareRouteImport } from './routes/baby-care'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ElderCareRouteImport } from './routes/elder-care'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HomeNursingRouteImport } from './routes/home-nursing'
import { Route as HospitalEscortRouteImport } from './routes/hospital-escort'
import { Route as HouseMaidRouteImport } from './routes/house-maid'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as PatientCareRouteImport } from './routes/patient-care'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ApiPublicProxySplatRouteImport } from './routes/api/public/proxy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AyaServicesRoute = AyaServicesRouteImport.update({
  id: '/aya-services',
  path: '/aya-services',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyCareRoute = BabyCareRouteImport.update({
  id: '/baby-care',
  path: '/baby-care',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElderCareRoute = ElderCareRouteImport.update({
  id: '/elder-care',
  path: '/elder-care',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeNursingRoute = HomeNursingRouteImport.update({
  id: '/home-nursing',
  path: '/home-nursing',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalEscortRoute = HospitalEscortRouteImport.update({
  id: '/hospital-escort',
  path: '/hospital-escort',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseMaidRoute = HouseMaidRouteImport.update({
  id: '/house-maid',
  path: '/house-maid',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientCareRoute = PatientCareRouteImport.update({
  id: '/patient-care',
  path: '/patient-care',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxySplatRoute = ApiPublicProxySplatRouteImport.update({
  id: '/api/public/proxy/$',
  path: '/api/public/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aya-services': typeof AyaServicesRoute
  '/baby-care': typeof BabyCareRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/elder-care': typeof ElderCareRoute
  '/faq': typeof FaqRoute
  '/home-nursing': typeof HomeNursingRoute
  '/hospital-escort': typeof HospitalEscortRoute
  '/house-maid': typeof HouseMaidRoute
  '/housekeeping': typeof HousekeepingRoute
  '/patient-care': typeof PatientCareRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aya-services': typeof AyaServicesRoute
  '/baby-care': typeof BabyCareRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/elder-care': typeof ElderCareRoute
  '/faq': typeof FaqRoute
  '/home-nursing': typeof HomeNursingRoute
  '/hospital-escort': typeof HospitalEscortRoute
  '/house-maid': typeof HouseMaidRoute
  '/housekeeping': typeof HousekeepingRoute
  '/patient-care': typeof PatientCareRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/careers': typeof CareersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aya-services': typeof AyaServicesRoute
  '/baby-care': typeof BabyCareRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/elder-care': typeof ElderCareRoute
  '/faq': typeof FaqRoute
  '/home-nursing': typeof HomeNursingRoute
  '/hospital-escort': typeof HospitalEscortRoute
  '/house-maid': typeof HouseMaidRoute
  '/housekeeping': typeof HousekeepingRoute
  '/patient-care': typeof PatientCareRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aya-services'
    | '/baby-care'
    | '/booking'
    | '/contact'
    | '/elder-care'
    | '/faq'
    | '/home-nursing'
    | '/hospital-escort'
    | '/house-maid'
    | '/housekeeping'
    | '/patient-care'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/videos'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/blogs/'
    | '/careers/'
    | '/services/'
    | '/api/public/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aya-services'
    | '/baby-care'
    | '/booking'
    | '/contact'
    | '/elder-care'
    | '/faq'
    | '/home-nursing'
    | '/hospital-escort'
    | '/house-maid'
    | '/housekeeping'
    | '/patient-care'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/videos'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/blog'
    | '/blogs'
    | '/careers'
    | '/services'
    | '/api/public/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aya-services'
    | '/baby-care'
    | '/booking'
    | '/contact'
    | '/elder-care'
    | '/faq'
    | '/home-nursing'
    | '/hospital-escort'
    | '/house-maid'
    | '/housekeeping'
    | '/patient-care'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/videos'
    | '/blog/$slug'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/blogs/'
    | '/careers/'
    | '/services/'
    | '/api/public/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AyaServicesRoute: typeof AyaServicesRoute
  BabyCareRoute: typeof BabyCareRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  ElderCareRoute: typeof ElderCareRoute
  FaqRoute: typeof FaqRoute
  HomeNursingRoute: typeof HomeNursingRoute
  HospitalEscortRoute: typeof HospitalEscortRoute
  HouseMaidRoute: typeof HouseMaidRoute
  HousekeepingRoute: typeof HousekeepingRoute
  PatientCareRoute: typeof PatientCareRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VideosRoute: typeof VideosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicProxySplatRoute: typeof ApiPublicProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aya-services': {
      id: '/aya-services'
      path: '/aya-services'
      fullPath: '/aya-services'
      preLoaderRoute: typeof AyaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby-care': {
      id: '/baby-care'
      path: '/baby-care'
      fullPath: '/baby-care'
      preLoaderRoute: typeof BabyCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elder-care': {
      id: '/elder-care'
      path: '/elder-care'
      fullPath: '/elder-care'
      preLoaderRoute: typeof ElderCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-nursing': {
      id: '/home-nursing'
      path: '/home-nursing'
      fullPath: '/home-nursing'
      preLoaderRoute: typeof HomeNursingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-escort': {
      id: '/hospital-escort'
      path: '/hospital-escort'
      fullPath: '/hospital-escort'
      preLoaderRoute: typeof HospitalEscortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-maid': {
      id: '/house-maid'
      path: '/house-maid'
      fullPath: '/house-maid'
      preLoaderRoute: typeof HouseMaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-care': {
      id: '/patient-care'
      path: '/patient-care'
      fullPath: '/patient-care'
      preLoaderRoute: typeof PatientCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/$': {
      id: '/api/public/proxy/$'
      path: '/api/public/proxy/$'
      fullPath: '/api/public/proxy/$'
      preLoaderRoute: typeof ApiPublicProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AyaServicesRoute: AyaServicesRoute,
  BabyCareRoute: BabyCareRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  ElderCareRoute: ElderCareRoute,
  FaqRoute: FaqRoute,
  HomeNursingRoute: HomeNursingRoute,
  HospitalEscortRoute: HospitalEscortRoute,
  HouseMaidRoute: HouseMaidRoute,
  HousekeepingRoute: HousekeepingRoute,
  PatientCareRoute: PatientCareRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  VideosRoute: VideosRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicProxySplatRoute: ApiPublicProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
